server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vue-test
    username: user
    password: user
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/vue-sidebar-test
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
jwt:
  auth:
    converter:
      client-id: vue-sidebar-test-client
      principle-attribute: preferred_username